name: tictactoe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  audioplayers: ^5.2.1
  desktop_window: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    #images
    - assets/images/sky.jpg
    - assets/images/beach.jpg
    - assets/images/3x3v.png
    - assets/images/6x6_9x9v_super.png
    - assets/images/6x6_9x9v.png
    - assets/images/11x11v.png
    - assets/images/15x15_21x21v.png
    - assets/images/bubble.jpeg
    - assets/images/bubble_x.jpeg
    - assets/images/bubble_o.jpg
    - assets/images/super_x.jpg
    - assets/images/super_o.png
    - assets/images/number_4.png
    - assets/images/number_5.png
    - assets/images/number_6.jpg
    - assets/images/number_7.png
    - assets/images/number_8.jpg
    - assets/images/number_9.jpg
    - assets/sounds/background_music.wav
    - assets/sounds/bubble_pop.wav
    - assets/sounds/click_sound_effect.mp3
    - assets/sounds/jackpot_sound_edit.mp3
    - assets/sounds/new_swoosh.mp3
